### ISSUE TITLE
Travis CI deployment builds are failing

### ISSUE THREAD

**Issue by pkgw** [conda-forge/rust-feedstock#134]
The Travis CI builds in pull requests seem to be working OK, but recent deployment builds of this feedstock have been failing:

- https://app.travis-ci.com/github/conda-forge/rust-feedstock/builds/262159440
  - https://github.com/conda-forge/rust-feedstock/runs/12632784275
- https://app.travis-ci.com/github/conda-forge/rust-feedstock/builds/262018768
- https://app.travis-ci.com/github/conda-forge/rust-feedstock/builds/260526609

They might just need to be retried, but I don't know how to trigger that. I think I used to be able to through the web UI, but I'm logged in through my GitHub account and can't see a way to trigger a retry right now.

**Comment by pkgw** [comment]
*Of course*, immediately after filing this, I noticed the way to retry the build through GitHub. I've done that, and we'll see what happens.

**Comment by pkgw** [comment]
@conda-forge/core When I log in to the Travis CI UI, I have permissions to do things like rerun builds on almost every conda-forge repo, but not `rust-feedstock` for some reason. Is anyone able to do anything about that? I'm hoping to clear the Travis cache for Rust in the (faint) hope that maybe it will unstick this build.

**Comment by pkgw** [comment]
Sloooooowly making progress here. Maybe.

- Asking the admin bot to update the GitHub team fixed my Travis CI permissions.
- It seems well established that on multi-arch builds, the logs will truncate extremely early on failed builds, and so are not useful guides for understand where the build is hanging; see Travis CI forum threads [A], [B].
- The implementation of the `travis_wait` command may be seen [here][tw].
- [This comment][1] seems to suggest that when (secret?) build variables are present, the output of the build process is not a TTY. My hunch is that the combination of this aspect, the truncation behavior of the LXD builds, and the implementation of `travis_wait` combine to make it so that deployment builds on non-standard arches that use `travis_wait` don't work as intended, causing the problem I've mentioned in the past few comments.

[A]: https://travis-ci.community/t/builds-hang-with-output-truncated-mid-line/7611
[B]: https://travis-ci.community/t/multiarch-builds-lxd-always-time-out-on-failure-instead-of-exit/7659
[tw]: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_wait.bash
[1]: https://travis-ci.community/t/builds-hang-with-output-truncated-mid-line/7611/8

**Comment by pkgw** [comment]
Aaargh. After merging #137, with a different workaround for the Travis CI timeouts, the ppc64le build succeeded but the arm64 build failed, with the "old" behavior of dying after about 16 minutes after output stalls at the end of the conda-build phase. (The "new" behavior with the `travis_wait` approach dies after 10+epsilon minutes during the deployment builds, seemingly with no output received at all during the main build phase.) Also the log of the (successful!) ppc64le build seems to be severely truncated.

Since one build succeeded, I've tried restarting the arm64 build just in case a second try works — not sure why the behavior here would be platform-dependent. But the overall picture here is one that, admittedly, we've known for a while: Travis CI is not working well as a platform for this work. I will try harder to see if we can get the cross-arch builds to work on another platform.

**Comment by jaimergp** [comment]
Thanks @pkgw, this is valuable feedback for https://github.com/conda-forge/conda-forge.github.io/issues/1521 and https://github.com/conda-forge/conda-forge.github.io/issues/1875

**Comment by pkgw** [comment]
Woohoo! In #138 it seems that [the mysterious errors][1] previously experienced on Azure are now gone. Azure builds are much slower than Travis, but hopefully they will actually succeed in production, and we can get our first new package of Rust for `linux-arm64` in several months.

[1]: https://github.com/conda-forge/rust-feedstock/pull/131#issuecomment-1495212821

**Comment by pkgw** [comment]
OK, it looks like Azure is working! Hopefully we can say goodbye to Travis CI in this feedstock.
