### ISSUE TITLE
Ability to cross-compile for "wasm32-unknown-unknown" target arch

### ISSUE THREAD

**Issue by ruben-arts** [conda-forge/rust-feedstock#153]
### Comment:

Hee all,

Thanks for putting rust on conda-forge!

I'm trying to build a rust package for conda-forge but it requires the target addition of `wasm32` to the possible build targets of cargo. 

Normally you would do this with `rustup`
```shell
rustup target add wasm32-unknown-unknown
```

But the rust installation doesn't include rustup. 

See [this PR](https://github.com/conda-forge/staged-recipes/pull/22471) for the problem

Is there a way to install this target that you know of? Otherwise would it make sense to make a feedstock for `rustup`?

**Comment by pkgw** [comment]
Hi @ruben-arts,

The way that the conda-forge packaging works, we would solve this problem in a way that doesn't involve `rustup`. We already support a number of cross-compilation targets with packages named like `rust-std-$ARCH`, and I believe that all we would need to do is add another such package. That's done by adding some additional entries to this repository's `meta.yaml` and `.ci_support/linux_64_.yaml`. Then, your package would depend on the new `rust-std-wasm2-unknown-unknown`. Would you be able to try implementing that yourself?

**Comment by ruben-arts** [comment]
He @pkgw,

This is exactly what I was curious at, I didn't read the source as if they where the target. 

I made the PR #154, hopefully I understood it correctly!

Thanks for the quick reaction!

**Comment by ruben-arts** [comment]
The merging of the PR fixed  the issue! Thanks for the help. One more problem remaining which I'm not understanding is that the windows build doesn't seem to work because it can't find the wasm32 target although it is installed in the build environment. Do you have any ideas why that could be? 

More info in these pipelines: https://github.com/conda-forge/staged-recipes/pull/22471/checks?check_run_id=15178302216

**Comment by isuruf** [comment]
The layouts for windows and unix are different, so we need two packages. See how we do the same for `rust-src` at https://github.com/conda-forge/rust-feedstock/blob/b9636f2a12abff9059b01bebee8721a718cce9e9/recipe/meta.yaml#L135-L149
. We need to do the same at https://github.com/conda-forge/rust-feedstock/blob/b9636f2a12abff9059b01bebee8721a718cce9e9/recipe/meta.yaml#L165-L173

**Comment by ruben-arts** [comment]
> The layouts for windows and unix are different, so we need two packages. See how we fix the same issue for `rust-src` at
> 
> https://github.com/conda-forge/rust-feedstock/blob/b9636f2a12abff9059b01bebee8721a718cce9e9/recipe/meta.yaml#L135-L149
> 
> 
> . We need to do the same at
> https://github.com/conda-forge/rust-feedstock/blob/b9636f2a12abff9059b01bebee8721a718cce9e9/recipe/meta.yaml#L165-L173

Great! Here is a PR : #155.

**Comment by isuruf** [comment]
Should be fixed now
