### ISSUE TITLE
Export `__glibc` runtime constraints?

### ISSUE THREAD

**Issue by charlesbluca** [conda-forge/rust-feedstock#192]
### Comment:

`rust` has a strong runtime constraint on `__osx>=10.12`:

https://github.com/conda-forge/rust-feedstock/blob/21b99fc7426c7f956520acb92357e25673d67b01/recipe/meta.yaml#L118-L120

Which I assume was motivated by the [bump to minimum supported Apple platform versions as of 1.74](https://blog.rust-lang.org/2023/09/25/Increasing-Apple-Version-Requirements.html).

Considering there was a similar [bump to the glibc minimum requirements as of 1.64.0](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html), does it make sense to introduce a similar runtime constraint for `__glibc`? Going off [this comment](https://github.com/rust-lang/rust/issues/125067#issuecomment-2107338216):

> Our glibc minimum is 2.17 and you have not followed the directions to cause conda to use the required glibc for linkage. You need to change the sysroot_linux-64 version. We raised the glibc requirements past 2.16 [in 2022](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html).

**Comment by pkgw** [comment]
This change was added in #194 (our package of Rust 1.78.0).
