### ISSUE TITLE
Add rust unstable with the dev label

### ISSUE THREAD

**Issue by rth** [conda-forge/rust-feedstock#31]
While the ability to install rust with conda is quite nice, something I have found limiting so far is the ability to install rust unstable needed for some packages/crates. 

As far as I understood, features currently in rust unstable have no guarantee of making into the stable, and so when those are needed by a crate, waiting for the next release of rust is not a viable solution.

In particular, rust unstable is currently required by https://github.com/PyO3/pyo3 (bindings for CPython C API) and as a result https://github.com/rust-numpy/rust-numpy (binding for numpy C API). Given the amount of Python package on conda-forge, I think it is quite important to be able to build a Python package with a "C" extension written in Rust.

If you think it's a good idea, I can (try) to make a PR to add rust unstable under e.g. [`dev` label](https://anaconda.org/conda-forge/repo?label=dev) (or some other non-default label).

**Comment by rth** [comment]
> What if a new feedstock for rust-nightly is created, and follow CalVer?

What would be the advantage of that compared e.g. to having a separate brach in this repo? I know that some repos (e.g. https://github.com/conda-forge/qt-feedstock) have two parallel branches, but I'm not sure if anything specific needs to be done to publish the built packages from the non master branch to the server as well.

> The main issue of using nightly in other feedstocks is that it is not uncommon to break code with new updates, but using the date for a "known good version" will keep the dependant feedstock working.

Right, but if it has a separate label, it will only be installed when the user explicitly provides
```
conda install --channel "conda-forge/label/dev" package
```
and a different version scheme could be done there I imagine without impacting the rust package on the main conda-forge channel (unless I'm missing something)?

**Comment by jakirkham** [comment]
Publishing under a different label using a different branch is how we prefer to handle RCs and such.

**Comment by pkgw** [comment]
How often would you want to update the unstable feedstock? Each set of Rust artifacts is about 750 MB, so daily updates might start getting to be a bit much even in these glorious days of The Cloud.

**Comment by rth** [comment]
Definitely not daily. Even a couple of times a year might do I think. For instance [pyo3](https://github.com/PyO3/pyo3) can be run with rust unstable 1.30 even if the latest stable version is 1.31. So it's not about getting the latest nightly, but rather having a compiler which has the unstable features even if it's from some time ago.

**Comment by rth** [comment]
Thanks.

The other solution is to wait for PyO3 to get rid of specialization feature which seems to be on [the roadmap](https://github.com/PyO3/pyo3/milestone/2) for the next release. That would allow building Python extensions with rust stable, and will make this issue no longer necessary as far as I am concerned..

**Comment by mariusvniekerk** [comment]
@pkgw Should we have a specialized rust-nightly package for things that need rust nightly instead?

**Comment by pkgw** [comment]
@mariusvniekerk Hmm, I think that might be the best approach. Could we implement a `rust-nightly` package as a branch of this same feedstock, but with a different package name in the `meta.yaml`? Having two different feedstock repos wouldn't be the end of the world, but their contents would be awfully similar so I think it would be better to keep them close together if possible.

**Comment by pkgw** [comment]
Fixed in #52, merged to the new `dev` branch as per new conda-forge recommendations for this sort of thing.
