### ISSUE TITLE
Relabeling dev releases from main to dev

### ISSUE THREAD

**Issue by andfoy** [conda-forge/rust-feedstock#53]
Hi @conda-forge/core,

Please move my package from ``main`` to ``dev`` on the conda-forge channel on anaconda.org
because:

It seems that we published nightly pre-releases (under the ``dev`` branch) under ``main`` labels, instead of ``dev`` ones. I'm aware that there seems to be some mistake on https://github.com/conda-forge/rust-feedstock/blob/dev/recipe/conda_build_config.yml, is it correct to replace

```yaml
channel_targets:
  - conda-forge rust_dev
```

by 

```yaml
channel_targets:
  - conda-forge/label/rust_dev
```

**Comment by ocefpaf** [comment]
Done: https://anaconda.org/conda-forge/rust/files?version=1.45.0.dev20200428

You can add a [conda_build_config.yaml](conda_build_config.yaml) to configure that for you and avoid uploading to `main`.

**Comment by jakirkham** [comment]
If you don't need `conda_build_config.yaml`, you could just drop it and re-render, which would also fix the issue. That said, IDK much about how `conda_build_config.yaml` is being used in this feedstock. So you might want to check it is only being used for the channel before deleting it.

**Comment by isuruf** [comment]
@jakirkham, that's bad advice. It's needed for dev.

@andfoy, yes you need a `conda_build_config.yaml` in `dev`, but not in `master`. What you have in `dev` is correct, but you are missing a rerender.

**Comment by pkgw** [comment]
@isuruf I've done a local rerender on the `dev` branch and it doesn't want to change anything. Is that expected?

**Comment by isuruf** [comment]
That's weird. The line at https://github.com/conda-forge/rust-feedstock/blob/dev/.ci_support/linux_.yaml#L8 should change.

**Comment by isuruf** [comment]
Ah, file name needs to be `conda_build_config.yaml` (not `conda_build_config.yml`)

**Comment by andfoy** [comment]
> Ah, file name needs to be conda_build_config.yaml (not conda_build_config.yml)

I'll correct it then! Thanks for pointing out!

**Comment by jakirkham** [comment]
> @jakirkham, that's bad advice. It's needed for dev.

Sorry I may have misunderstood. Thought they wanted things in `main` instead of `dev`.
