### ISSUE TITLE
Cross-compilation targets

### ISSUE THREAD

**Issue by photex** [conda-forge/rust-feedstock#61]
Howdy!

With rustup we can use `target add <llvm-taret-triple>` to get a suitable version of the std crate to enable cross-compilation.

Is this in-scope for this feedstock to be expanded to support adding these targets so that we can rely on conda-forge rather than require rustup (CI in particular will benefit tremendously).

**Comment by pkgw** [comment]
My opinion would be that such targets shouldn't be added to the `rust` package — that should be the core Rust toolchain targeted at the build host. But it might make sense to add cross-compilation toolchains as additional packages (e.g. `rust-target-arm-unknown-linux-gnu`?). And depending on the packaging, it might make sense to implement those in this feedstock with one recipe generating multiple output packages.

There should be prior art here from the C/C++ toolchains ... how do the conda(-forge) compiler packages handle cross-compilation, if they do so at all?

Also, why do you think that this will offer significant benefits over rustup? Rustup is pretty quick to install and will be downloading about the same amount of data, no?

**Comment by photex** [comment]
> But it might make sense to add cross-compilation toolchains as additional packages (e.g. rust-target-arm-unknown-linux-gnu?).

I should have been more clear, but this is exactly how I pictured this would work.

> how do the conda(-forge) compiler packages handle cross-compilation

Good question. But I'm happy to dig in a bit and see if I can wrestle up a working example of how to proceed. I see sysroot packages for aarch64, and compilers, any cross targets would likely also depend on those. Hard to say where to draw the line until I understand a bit more.

> Also, why do you think that this will offer significant benefits over rustup? Rustup is pretty quick to install and will be downloading about the same amount of data, no?

You could say the same thing about this feedstock as well couldn't you? I think there is value in specifying that a project builds with a specific rust compiler version and can target multiple architectures. If you're already using the conda environment to setup your C++ toolchains rather than relying on what comes with apt and so on, it's a small step to consider Rust the same way.
I think conda is a pretty nice way to make sure that a development environment for a product is formally aligned between members of a team.

**Comment by pkgw** [comment]
@photex Thanks, it would be great if you could look into the existing patterns a bit. I know that the conda build framework supports cross compilation decently at this point, but quickly scanning through the existing docs I'm not seeing a ton of obvious info about how the support stuff should be packaged. As per [this](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html), the C/C++ toolchain uses compiler executables named `$TARGET-cc`, etc., but I don't know which x86_64 Linux package would contain (e.g.) `aarch64-unknown-linux-gnu-cc`. It may be the case that any existing infrastructure is too specialized to the `$TARGET-$TOOL` scheme to map well to Rust, which uses a different approach, but it's worth looking into.

Anyway, if we can package up the infrastructure that will help make it easy to cross-compile Rust programs within the conda-build framework, that will indeed be helpful.

**Comment by isuruf** [comment]
You can now cross compile from `linux-64` to `linux-ppc64le, linux-aarch64, osx-64`. Install `rust_osx-64` on a new env to cross compile for osx-64

**Comment by bigbrett** [comment]
I see this issue is closed, but I'm curious what the plan for supporting other LLVM cross-compilation targets is? I want to use conda to manage consistent development environments across engineers (and be able to just send an `environment.yml` file to a manufacturer to allow them to build our code without manually installing all the toolchain stuff. 

Is there currently a way to use this conda package to get cross compilation for ARM cortex M targets (`thumbv7em-none-eabihf` and `thumbv8m.main-none-eabihf` specifically)?

Normally, I would just use `rustup toolchain install thumbv7em-none-eabihf` and all would be well. Is there an analog for the conda package?

**Comment by isuruf** [comment]
In theory you could add support, but we currently don't have support and no plans to add them either.

**Comment by bigbrett** [comment]
What would adding support for this entail?

And any reason why there are no plans for it? Seems like the use case for it is pretty well informed based on this thread and how people want to use conda to manage dev environments…

**Comment by isuruf** [comment]
> What would adding support for this entail?

It depends on the target really. I don't know anything about `thumbv7em-none-eabihf` target. You'll need to first package the C library (I assume it's not glibc) as a conda package so that the linker can do its job. Then you'll have to package the `rust-std` here. Then you'll have to add support to `rust-activation-feedstock`.

> And any reason why there are no plans for it?

1. No time.
2. conda doesn't support these platforms.
